# Generated by Django 2.0.2 on 2019-02-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.Application'),
        ),
        migrations.AlterField(
            model_name='node',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.Customer'),
        ),
        migrations.AlterField(
            model_name='node',
            name='firmware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.Firmware'),
        ),
        migrations.AlterField(
            model_name='node',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.Location'),
        ),
    ]
