# Generated by Django 2.0.2 on 2019-02-25 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0002_auto_20190224_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='lastpingstate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.OnlineState'),
        ),
        migrations.AlterField(
            model_name='node',
            name='pingintervalmillis',
            field=models.IntegerField(),
        ),
    ]
