# Generated by Django 2.0.2 on 2019-02-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0003_auto_20190224_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='lastpingtimestamp',
            field=models.DateTimeField(null=True, verbose_name='Last Ping Time'),
        ),
    ]
