# Generated by Django 2.0.2 on 2019-02-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0004_auto_20190224_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorState',
            fields=[
                ('idsensorstate', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
            ],
        ),
    ]
