# Generated by Django 2.0.2 on 2019-02-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0005_sensorstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorState',
        ),
    ]
