# Generated by Django 2.0.2 on 2019-02-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0006_delete_sensorstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('idnodetype', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=32)),
                ('shorttag', models.CharField(default='none', max_length=32)),
            ],
        ),
    ]
