# Generated by Django 2.0.2 on 2019-02-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0007_nodetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='nodetype',
            field=models.ForeignKey(default=10000, null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.NodeType'),
        ),
    ]
