# Generated by Django 2.0.2 on 2019-02-27 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0008_node_nodetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('idchannel', models.BigAutoField(primary_key=True, serialize=False)),
                ('uplink', models.IntegerField()),
                ('dnlink', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('idsensor', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=24)),
                ('node', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kanji.Node')),
                ('sensortype', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kanji.SensorType')),
            ],
        ),
    ]
