# Generated by Django 2.0.2 on 2019-03-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0010_auto_20190226_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='eventdata',
            field=models.CharField(max_length=622),
        ),
    ]
