# Generated by Django 2.0.2 on 2019-03-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0011_auto_20190318_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='name',
        ),
    ]
