# Generated by Django 2.0.2 on 2019-03-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0012_remove_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=64),
        ),
    ]
