# Generated by Django 2.0.2 on 2019-03-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0013_auto_20190318_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='setupstring',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
