# Generated by Django 2.0.2 on 2019-03-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0016_node_gridlocator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slacktoken',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='slackchannel',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
