# Generated by Django 2.0.2 on 2019-03-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0017_auto_20190321_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slacktoken',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
