# Generated by Django 2.0.2 on 2019-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0019_node_friendlyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slackadminpass',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='slackadminuser',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='slackworkspace',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
