# Generated by Django 2.0.2 on 2019-08-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0020_auto_20190813_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
