# Generated by Django 2.0.2 on 2019-09-17 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0021_auto_20190830_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('idurgency', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=24)),
                ('lastname', models.CharField(max_length=24)),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
            ],
        ),
        migrations.RenameModel(
            old_name='EventType',
            new_name='Impact',
        ),
        migrations.RenameField(
            model_name='impact',
            old_name='ideventtype',
            new_name='idimpact',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='eventtype',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='acktimestamp',
            field=models.DateTimeField(null=True, verbose_name='DateTime'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='impact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.Impact'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='ackuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.User'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.Urgency'),
        ),
    ]
