# Generated by Django 2.0.2 on 2019-09-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0023_auto_20190917_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('idissue', models.BigAutoField(primary_key=True, serialize=False)),
                ('opentimestamp', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('acktimestamp', models.DateTimeField(null=True, verbose_name='DateTime')),
                ('closetimestamp', models.DateTimeField(null=True, verbose_name='DateTime')),
                ('ackuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.User')),
                ('impact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.Impact')),
            ],
        ),
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('idissuestatus', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=24)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='acktimestamp',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='ackuser',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='urgency',
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.IssueStatus'),
        ),
        migrations.AddField(
            model_name='issue',
            name='urgency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.Urgency'),
        ),
    ]
