# Generated by Django 2.0.2 on 2019-09-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0025_auto_20190917_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='maxo2pct',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='location',
            name='maxpsi',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='location',
            name='maxrssidb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='maxtempf',
            field=models.IntegerField(default=95),
        ),
        migrations.AddField(
            model_name='location',
            name='maxvolts',
            field=models.IntegerField(default=140),
        ),
        migrations.AddField(
            model_name='location',
            name='mino2pct',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='location',
            name='minpsi',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='location',
            name='minrssidb',
            field=models.IntegerField(default=-78),
        ),
        migrations.AddField(
            model_name='location',
            name='mintempf',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='location',
            name='minvolts',
            field=models.IntegerField(default=100),
        ),
    ]
