# Generated by Django 2.0.2 on 2019-09-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0027_auto_20190918_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueStatus',
            new_name='TicketStatus',
        ),
    ]
