# Generated by Django 2.0.2 on 2019-09-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0029_auto_20190918_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('idtickettype', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kanji.TicketType'),
        ),
    ]
